[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci --omit=dev --ignore-scripts"]

[phases.build]
cmds = [
  "npm install --save-dev prisma @nestjs/cli",
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npx prisma migrate deploy && node dist/main"
